LICENS-91 BE: Update available is showing after you enter a valid key, even when there isn’t an update available
stellarwp/uplink pull request #28
Opened 2023-08-11 15:17 UTC by MlKilderkin

## What 
Show new version message available only if installed version lower then version in response

https://moderntribe.atlassian.net/browse/LICENS-91

2023-08-11 18:36 UTC, borkweb approved these changes

2023-08-14 08:20 UTC, MlKilderkin commented
@jamesckemp @borkweb this should be reviewed with https://github.com/stellarwp/licensing/pull/43

2023-08-14 14:09 UTC, borkweb requested changes

2023-08-14 14:09 UTC, borkweb commented on src/Uplink/Messages/Update_Available.php
> +				$link,
```suggestion
			$link,
```

2023-08-16 19:30 UTC, jamesckemp requested changes
The original issue is fixed. However, there’s another scenario which a. has a fatal error, and b. probably shows the wrong message.

1. If you enter a key for the first time and an **update is available**. there’s a fatal error. This is because I haven’t entered a home URL anywhere and it’s expecting a string response. That can be fixed with a type declaration:

```
	/**
	 * Get home URL.
	 *
	 * @return string|null
	 */
	public function get_home_url(): ?string {
		return $this->home_url;
	}
```

Related: Where would I set the home URL and at what point?

2. With that fix in place, if I enter a valid key and an **update is available**, it says:

`There is an update for Flux Checkout. You'll need to check your license to have access to updates, downloads, and support.`

Why do I need to check my license if it’s valid and an update is available?

2023-08-17 07:58 UTC, MlKilderkin commented
Hello @jamesckemp 
The 1st issue is resolved
Regarding the second, we probably just should change the wordings (@borkweb maybe you could help us here)

2023-08-28 14:09 UTC, borkweb approved these changes

2023-08-31 13:01 UTC, jamesckemp approved these changes

2023-08-31 13:01 UTC, merged