[LICENS-45]: Token auth
stellarwp/uplink pull request #36
Opened 2023-09-15 21:10 UTC by defunctl

2023-10-19 17:29 UTC, defunctl commented on src/Uplink/Admin/Notice.php
> -	protected array $saved_notices = [];
These were added previously by another developer, technically this project does not support the minimum of [PHP7.4](https://github.com/stellarwp/uplink/blob/29306946e41fcc21d3c8a44801e62789acc55705/composer.json#L31)

2023-10-19 22:18 UTC, defunctl commented on src/Uplink/Register.php
> +	public static function plugin( $slug, $name, $version, $path, $class, $license_class = null ) {
These variables were in the correct order, but they were named for the wrong things, so I swapped them.

If you follow the chain this creates, all the `register()` methods take a slug first and this matches the current documentation in the README.

e.g.

```php
Register::plugin(
	$plugin_slug,
	$plugin_name,
	$plugin_version,
	$plugin_path,
	$plugin_class,
	$license_class // This is optional.
);

Register::service(
	$service_slug,
	$service_name,
	$service_version,
	$plugin_path,
	$plugin_class
);
```

2023-10-20 13:36 UTC, borkweb requested changes
There's a bunch of great stuff in this code! Nice changes. A few notes:

## Anonymous functions for actions

As a whole, we need to avoid using anonymous functions for actions because everything needs to be unhookable / movable. Our default flow that we believe is fine, may not actually be viable on some sites and we need to give those sites the ability to change or manipulate the actions.

## League Plates

We cannot introduce that library into the uplink library. That's too opinionated of a tool for the job. If this was an internal library for our own sites, it'd be one thing. Because it will be used on multiple brand products and then those will be distributed out in the wild, adopting something like this needs a broader discussion.

## Docblocks on constructors

We standardize on having them.

## Translations for exceptions

Historically, WordPress, WooCommerce, TEC, etc did not run exception strings through translate functions. However, the newer code of WP and WC do. I think we should follow suit and support non-english developers by translating Exception strings. There were a few exceptions that were altered (but pre-existing) that I went ahead and added a code suggestion for that adds translation functions as a wrapper.

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Authorizer.php
> +	public function __construct( Pipeline $pipeline ) {
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Nonce.php
> +	public const NONCE_SUFFIX = '_uplink_nonce';
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Nonce.php
> +	private function key(): string {
Docblocks

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Provider.php
> +	private function register_nonce(): void {
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Provider.php
> +	}
Two things here.

1. Docblocks
2. To be a good WordPress citizen, these actions need to be unhookable, so we cannot use anonymous functions here. While we feel that this logic belongs in `admin_init`, an end user of our plugins might have a weird situation where that isn't viable, so providing a situation where they can unhook and re-hook to the action of their choosing is important.

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Token/Connector.php
> +	public function __construct(
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Token/Contracts/Token_Manager.php
> +
```suggestion
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Token/Disconnector.php
> +	public function __construct(
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Token/Token_Manager.php
> +	public function __construct( string $option_name ) {
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Auth/Token/Token_Manager.php
> +			throw new InvalidArgumentException( 'You must set a token prefix with StellarWP\Uplink\Config::set_token_auth_prefix() before using the token manager.' );
```suggestion
			throw new InvalidArgumentException( __( 'You must set a token prefix with StellarWP\Uplink\Config::set_token_auth_prefix() before using the token manager.', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Components/Admin/Authorize_Button_Controller.php
> +	public function __construct(
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Components/Admin/Authorize_Button_Controller.php
> +			throw new InvalidArgumentException( 'The Product slug cannot be empty' );
```suggestion
			throw new InvalidArgumentException( __( 'The Product slug cannot be empty', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Config.php
> +			throw new RuntimeException( 'You must provide a container via StellarWP\Uplink\Config::set_container() before attempting to fetch it.' );
Oops. Not having exceptions in this class file translated before was an oversight.

```suggestion
			throw new RuntimeException( __( 'You must provide a container via StellarWP\Uplink\Config::set_container() before attempting to fetch it.', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Config.php
> +			throw new RuntimeException( 'You must provide a hook prefix via StellarWP\Uplink\Config::set_hook_prefix() before attempting to fetch it.' );
```suggestion
			throw new RuntimeException( __( 'You must provide a hook prefix via StellarWP\Uplink\Config::set_hook_prefix() before attempting to fetch it.', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Config.php
> +			throw new RuntimeException( 'You must provide a hook prefix via StellarWP\Uplink\Config::set_hook_prefix() before attempting to fetch it.' );
```suggestion
			throw new RuntimeException( __( 'You must provide a hook prefix via StellarWP\Uplink\Config::set_hook_prefix() before attempting to fetch it.', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Config.php
> +			throw new RuntimeException( 'You must set a container with StellarWP\Uplink\Config::set_container() before setting a token auth prefix.' );
```suggestion
			throw new RuntimeException( __( 'You must set a container with StellarWP\Uplink\Config::set_container() before setting a token auth prefix.', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Config.php
> +					'The token auth prefix must be at most %d characters, including a trailing hyphen.',
```suggestion
					__( 'The token auth prefix must be at most %d characters, including a trailing hyphen.', '%TEXTDOMAIN%' ),
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Notice/Notice.php
> +	public function __construct(
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Notice/Notice.php
> +					'Notice $type must be one of: %s',
```suggestion
					__( 'Notice $type must be one of: %s', '%TEXTDOMAIN%' ),
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Notice/Notice.php
> +			throw new InvalidArgumentException( 'The $message cannot be empty' );
```suggestion
			throw new InvalidArgumentException( __( 'The $message cannot be empty', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Notice/Provider.php
> +		}, 12, 0 );
This cannot be an anonymous function. It needs to be easily unhookable.

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Traits/With_Debugging.php
> +	protected function is_wp_debug(): bool {
Docblock

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Uplink.php
> +			throw new RuntimeException( 'You must call StellarWP\Uplink\Config::set_container() before calling StellarWP\Telemetry::init().' );
```suggestion
			throw new RuntimeException( __( 'You must call StellarWP\Uplink\Config::set_container() before calling StellarWP\Telemetry::init().', '%TEXTDOMAIN%' ) );
```

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/View/Provider.php
> +use League\Plates\Engine;
I think it is too heavy handed to be introducing a templating engine as a dependency into this uplink library.

2023-10-20 13:36 UTC, borkweb commented on src/views/admin/authorize-button.php
> + * @var \League\Plates\Template\Template $this
We'll need to remove this.

2023-10-20 13:36 UTC, borkweb commented on src/views/admin/notice.php
> + * @var \League\Plates\Template\Template $this
Remove

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Components/Admin/Authorize_Button_Controller.php
> +use League\Plates\Engine;
We'll need to remove this.

2023-10-20 13:36 UTC, borkweb commented on src/Uplink/Components/Controller.php
> +use League\Plates\Engine;
We'll need to remove this

2023-10-20 15:36 UTC, defunctl commented on src/Uplink/API/Client.php
> +	protected $api_root = '/api/plugins/v2/';
Removed the translations.

2023-10-20 15:49 UTC, defunctl commented on src/Uplink/API/Client.php
> +	protected $api_root = '/api/plugins/v2/';
Completely agree and I did the same check :grin:

2023-10-20 15:57 UTC, defunctl commented on src/Uplink/Auth/Admin/Disconnect_Controller.php
> +		if ( wp_verify_nonce( $_GET['_wpnonce'], self::ARG ) ) {
TIL

2023-10-23 13:41 UTC, borkweb approved these changes

2023-10-24 19:15 UTC, borkweb approved these changes

2023-10-24 20:56 UTC, merged