Prevent fatal during update prevention when $source is a WP_Error rather than a string
stellarwp/uplink pull request #61
Opened 2024-01-11 11:03 UTC by davegreenwp

Iconic support encountered a ticket where a customer has attempted to upgrade to WC `8.5.0` and received a fatal error:

![image](https://github.com/stellarwp/uplink/assets/3214928/ac53bdce-0564-4e7f-8ec4-b42030d2d91c)

The issue is that the `filter_upgrader_source_selection_for_update_prevention` method is not checking to see if `$source` is a `WP_Error`. In this case, we believe that the error is is being thrown by an [issue ](https://github.com/woocommerce/woocommerce/issues/43406) in this new WC release.

They have rolled back to a previous stable version in order to resolve their issue, but it would be good to defend against similar circumstances in the future.

This change simply adds a defensive check and returns a `WP_Error` with a generic message (text TBC).

2024-01-11 11:09 UTC, davegreenwp commented on src/Uplink/Admin/Provider.php
> +				esc_html__( 'Your update failed due to an unknown error.', '%TEXTDOMAIN%' ),
Specific text needs confirming. Perhaps this could be a little more specific i.e. reference that the error is coming from a different plugin? 🤔

2024-01-17 19:37 UTC, borkweb requested changes

2024-01-17 19:37 UTC, borkweb commented on src/Uplink/Admin/Provider.php
> +		}
Maybe we just return the WP_Error if we have it and not change the error message:

```suggestion
		if ( is_wp_error( $source ) ) {
			return source;
		}
```

2024-01-17 19:44 UTC, davegreenwp commented on src/Uplink/Admin/Provider.php
> +				esc_html__( 'Your update failed due to an unknown error.', '%TEXTDOMAIN%' ),
No longer required.

2024-01-17 19:45 UTC, borkweb commented on src/Uplink/Admin/Provider.php
> +			return source;
```suggestion
			return $source;
```

2024-01-17 19:58 UTC, merged